print ("my name is andrew")
print ("i like winning")
print(" (\___/)")
print("  \* */")
print("   \ /")
print("    o")
print ("andrew")
print("7")
print("a b = c")
print ("b c = 20")
print ("c d = a + b"")
print ("d e = f + d")
print ("e")
